name: 'build'

on:
  push:
    # Only used for build stage.
    branches:
    - main
    paths-ignore:
    - '*.md'
    - '*.png'
    # Publish 1.2.3 and 'latest' tags as releases.
    tags:
    - 'v?[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
    - main
    paths-ignore:
    - '*.md'
    - '*.png'
    types: [opened, synchronize, reopened] # https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull_request
  workflow_dispatch:
    inputs:
      reason:
        description: 'The reason for running the workflow.'
        required: true
        default: 'Manual run'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    # Map a step output to a job output.
    outputs:
      aws-base-image: ${{ steps.aws-base-image.outputs.changed }}

    steps:
    - uses: actions/checkout@v4
      with:
        # Disabling shallow clone is recommended for improving relevancy.
        fetch-depth: 0

    - name: Prepare Environment
      run: |
        NAME=$(basename -s .git "`git config --get remote.origin.url`")
        echo "REPO_NAME=$NAME" >> $GITHUB_ENV

    - name: Build Test Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: false
        load: true
        tags: ${{ env.REPO_NAME }}:test

    - name: Run Image Test
      run: |
        docker run --rm --entrypoint "/usr/local/bin/aws" $REPO_NAME:test --version

    - name: Check for New Base Image
      if: "!startsWith(github.ref, 'refs/tags/')"
      id: aws-base-image
      run: |
        AWS_CWL_EXPORTER_VERSION=$(curl -L -s 'https://registry.hub.docker.com/v2/repositories/stevenjdh/aws-cwl-exporter/tags?page_size=5'|jq -r '.results[4]["name"]')
        AWS_IMAGE_VERSION=$(curl -L -s 'https://registry.hub.docker.com/v2/repositories/amazon/aws-cli/tags?page_size=1'|jq -r '.results[]["name"]')

        if [[ "$AWS_CWL_EXPORTER_VERSION" == "$AWS_IMAGE_VERSION" ]]; then
            echo "No new build for $AWS_IMAGE_VERSION needed."
            echo "changed=false" >> $GITHUB_OUTPUT
        else
            echo "::notice::Build for $AWS_IMAGE_VERSION needed. Current version is $([[ $AWS_CWL_EXPORTER_VERSION != null ]] && echo $AWS_CWL_EXPORTER_VERSION || echo 'missing')."
            echo "changed=true" >> $GITHUB_OUTPUT
        fi
      continue-on-error: true

    - name: Upload Artifact
      if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v4
      with:
        name: repo-src
        path: |
          ${{ github.workspace }}
          !.git/
          !.github/
          !*.md
        retention-days: 1

  push_to_registries:
    name: Deploy Containers
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    environment: prod
    if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/')
    needs: build

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: repo-src

    - name: Generate Docker Metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        # List of container registry names to use for image tagging.
        # Everything will be automatically set to lowercase.
        images: |
          public.ecr.aws/${{ github.repository }},enable=true
          docker.io/${{ github.repository }},enable=true
          ghcr.io/${{ github.repository }},enable=true
        # Generates Docker tags based on the following events/attributes.
        tags: |
          type=ref,event=branch,enable=false
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Login to AWS Public ECR
      uses: docker/login-action@v3
      with:
        registry: public.ecr.aws
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      env:
        # Must be us-east-1 for requesting authentication token.
        # Reference: https://docs.aws.amazon.com/AmazonECR/latest/public/getting-started-cli.html#cli-authenticate-registry
        AWS_REGION: us-east-1

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build, Tag, and Push Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}